### PR TITLE
updated numpy

### PR DESCRIPTION
**Pull request by maikia**
Updated numpy part for workshop in 2019

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Some quick things:

- `index.ipynb` is missing (not sure it should be added, but at least the 'numpy_intro' notebook links to it
- we probably want to make sure all kernels are called "python3" to avoid that people get the "No kernel" pop up (not sure if this is important, but noticed it because different notebooks now ask for a different kernel, vs python3 vs py36)
- the exercise in `dataset_intro` might be a bit difficult? As they didn't see yet `np.argmin` and `np.abs` (or any of  the element-wise operations). So maybe limit the exercise to some things with indexing?
- the drawing used in kmeans is missing
- In the "operations" notebook, I might do some extra exercises

**Comment by maikia** [comment]
Thanks! here are the changes:
- I changed link to 'index.ipynb' to point to '../01-numpy-introduction.ipynb'
- Kernels are changed to python3
- I moved exercise from dataset_intro to operations + added simpler excercise to dataset_intro 
- added new excercise to operations
- added the directory /images with the images used in the notebooks
- I moved K-means clustering to extra topics

**Comment by jorisvandenbossche** [comment]
Some more comments:

- in the list vs array section (numpy_intro), I would include a `%timeit` comparing an operation on lists vs arrays (eg see https://nbviewer.jupyter.org/github/jorisvandenbossche/DS-python-data-analysis/blob/master/notebooks/python_recap/05-numpy.ipynb#Speed)
- dataset_intro: exercise: it is not fully clear from the explanation that you need to create a 2D array (or maybe the formatting went wrong for me in jupyter lab, because I see in the plain text it was formatted as a 2D array)
- Same exercise: "use `a` to assign 4, 1 and 3 to array `b` " -> maybe add "from the third row", as there is a 4 in one of the other rows as well
- PEP8: `patient0_data[patient0_data>10]` -> `patient0_data[patient0_data > 10]`  (in filtering_data)
- The copy or view quiz: we didn't really explain yet the difference I think? I am with having it in there (because it is sometimes an important notion), but just be prepared to explain it at that moment then :)
- Operations notebook: "It's also possbile to average over a single axis:". Maybe it would be good to explain "axis" a bit more, as this can be a confusing topic (scipy lectures notes has picture for it: https://scipy-lectures.org/intro/numpy/operations.html#basic-reductions, you could use that or link to it)

**Comment by glemaitre** [comment]
A couple of comments:

* I would remove the requirements since that we have the `check_env.py`
* We are going to use `jupyter lab` instead of `jupyter notebook`. Could make the changes accordingly.
* In the command list, you can add the `?` to get the help within a notebook.
* You should use a tuple to specify the size in `np.reshape`. It is working to say `np.reshape(4, 3)`. However, if someone wants something like that `np.reshape(4, 3, 3), this will crash.
* For the exercise to assign values, we can maybe give strict indications: which indices to use to insert the values.

**Pull request merged**
